-- Expand coding_tools from 34 to 100+ entries
-- Categories: mcp_server, ide_extension, cli_tool, framework, agent, web_tool, skill

-- ═══ MCP Servers ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, github_url, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Brave Search MCP', 'brave-search-mcp', 'mcp_server', 'search', 'MCP server for Brave web search with AI-ready results', 'Web search via Brave API', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search'),
('Memory MCP', 'memory-mcp', 'mcp_server', 'memory', 'Persistent memory for AI assistants using knowledge graph', 'Knowledge graph memory for AI', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory'),
('Fetch MCP', 'fetch-mcp', 'mcp_server', 'web', 'MCP server for fetching web content and converting to markdown', 'Fetch URLs as markdown', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch'),
('SQLite MCP', 'sqlite-mcp', 'mcp_server', 'database', 'Query and manage SQLite databases through MCP', 'SQLite database access', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite'),
('Google Drive MCP', 'google-drive-mcp', 'mcp_server', 'storage', 'Search and read Google Drive documents via MCP', 'Google Drive integration', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-drive'),
('Google Maps MCP', 'google-maps-mcp', 'mcp_server', 'location', 'Geocoding, directions, and place search via Google Maps API', 'Google Maps API access', 'https://github.com/modelcontextprotocol/servers', 'universal', 'freemium', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps'),
('Sentry MCP', 'sentry-mcp', 'mcp_server', 'monitoring', 'Access Sentry error tracking data via MCP', 'Sentry error monitoring', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/sentry'),
('Exa MCP', 'exa-mcp', 'mcp_server', 'search', 'Neural search engine for finding relevant content', 'AI-powered semantic search', 'https://github.com/exa-labs/exa-mcp-server', 'universal', 'freemium', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/exa-labs/exa-mcp-server'),
('Firecrawl MCP', 'firecrawl-mcp', 'mcp_server', 'web', 'Web scraping and crawling optimized for LLM consumption', 'AI-ready web scraping', 'https://github.com/mendableai/firecrawl-mcp-server', 'universal', 'freemium', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/mendableai/firecrawl-mcp-server'),
('Sequential Thinking MCP', 'sequential-thinking-mcp', 'mcp_server', 'reasoning', 'Dynamic chain-of-thought reasoning for complex problems', 'Step-by-step reasoning tool', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking'),
('Cloudflare MCP', 'cloudflare-mcp', 'mcp_server', 'infrastructure', 'Manage Cloudflare Workers, KV, R2, and D1 via MCP', 'Cloudflare platform access', 'https://github.com/cloudflare/mcp-server-cloudflare', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/cloudflare/mcp-server-cloudflare'),
('Playwright MCP', 'playwright-mcp', 'mcp_server', 'testing', 'Browser automation and testing via Playwright', 'Browser automation for testing', 'https://github.com/anthropics/mcp-playwright', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/anthropics/mcp-playwright'),
('Linear MCP', 'linear-mcp', 'mcp_server', 'project-management', 'Manage Linear issues, projects, and cycles via MCP', 'Linear project management', 'https://github.com/jerhadf/linear-mcp-server', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/jerhadf/linear-mcp-server'),
('Obsidian MCP', 'obsidian-mcp', 'mcp_server', 'notes', 'Read and write Obsidian vault notes via MCP', 'Obsidian note access', 'https://github.com/smithery-ai/mcp-obsidian', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/smithery-ai/mcp-obsidian'),
('Docker MCP', 'docker-mcp', 'mcp_server', 'containers', 'Manage Docker containers and images through MCP', 'Docker container management', 'https://github.com/ckreiling/mcp-server-docker', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/ckreiling/mcp-server-docker'),
('Notion MCP', 'notion-mcp', 'mcp_server', 'notes', 'Search and manage Notion pages and databases via MCP', 'Notion workspace access', 'https://github.com/modelcontextprotocol/servers', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/modelcontextprotocol/servers'),
('Supabase MCP', 'supabase-mcp', 'mcp_server', 'database', 'Query and manage Supabase databases and auth via MCP', 'Supabase backend access', 'https://github.com/supabase/mcp-server-supabase', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/supabase/mcp-server-supabase'),
('Neon MCP', 'neon-mcp', 'mcp_server', 'database', 'Manage Neon serverless Postgres branches and queries', 'Neon Postgres management', 'https://github.com/neondatabase/mcp-server-neon', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/neondatabase/mcp-server-neon'),
('Context7 MCP', 'context7-mcp', 'mcp_server', 'docs', 'Up-to-date library documentation for AI coding assistants', 'Live documentation lookup', 'https://github.com/upstash/context7', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/upstash/context7'),
('Todoist MCP', 'todoist-mcp', 'mcp_server', 'productivity', 'Manage Todoist tasks and projects via MCP', 'Todoist task management', 'https://github.com/abhiz123/todoist-mcp-server', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://github.com/abhiz123/todoist-mcp-server');

-- ═══ IDE Extensions / Editors ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Zed Editor', 'zed-editor', 'ide_extension', 'editor', 'High-performance code editor with built-in AI assistant supporting multiple LLM providers', 'Fast editor with AI assistant', 'universal', 'free', 'easy', '["claude-sonnet-4","gpt-4o","any-via-api"]', 'https://zed.dev'),
('Void Editor', 'void-editor', 'ide_extension', 'editor', 'Open-source AI code editor built as a fork of VS Code with native AI integration', 'Open-source AI code editor', 'universal', 'free', 'easy', '["claude-sonnet-4","gpt-4o","any-via-api"]', 'https://voideditor.com'),
('Trae IDE', 'trae-ide', 'ide_extension', 'editor', 'AI-native IDE by ByteDance with Claude and GPT model support', 'ByteDance AI IDE', 'universal', 'free', 'easy', '["claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://www.trae.ai'),
('PearAI', 'pearai', 'ide_extension', 'editor', 'Open-source AI code editor with integrated chat and autocomplete', 'Open-source AI editor', 'universal', 'freemium', 'easy', '["claude-sonnet-4","gpt-4o","any-via-api"]', 'https://trypear.ai'),
('Supermaven', 'supermaven', 'ide_extension', 'autocomplete', 'Ultra-fast AI code completion with 1M token context window', 'Fast AI autocomplete', 'universal', 'freemium', 'easy', '["any"]', 'https://supermaven.com'),
('Codeium', 'codeium', 'ide_extension', 'autocomplete', 'Free AI code completion and chat for 70+ languages', 'Free AI code assistant', 'universal', 'free', 'easy', '["any"]', 'https://codeium.com'),
('Sourcegraph Cody', 'sourcegraph-cody', 'ide_extension', 'assistant', 'AI coding assistant with full codebase context from Sourcegraph', 'Codebase-aware AI assistant', 'universal', 'freemium', 'easy', '["claude-sonnet-4","gpt-4o"]', 'https://sourcegraph.com/cody'),
('JetBrains AI', 'jetbrains-ai', 'ide_extension', 'assistant', 'AI assistant integrated into all JetBrains IDEs', 'JetBrains native AI', 'universal', 'paid', 'easy', '["claude-sonnet-4","gpt-4o","gemini-2.5-pro"]', 'https://www.jetbrains.com/ai/'),
('Qodo (formerly Codium)', 'qodo', 'ide_extension', 'testing', 'AI-powered test generation and code integrity platform', 'AI test generation', 'universal', 'freemium', 'easy', '["any"]', 'https://www.qodo.ai'),
('CodeGPT', 'codegpt', 'ide_extension', 'assistant', 'VS Code extension connecting to multiple AI providers for code assistance', 'Multi-provider AI for VS Code', 'universal', 'freemium', 'easy', '["claude-sonnet-4","gpt-4o","any-via-api"]', 'https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt'),
('Blackbox AI', 'blackbox-ai', 'ide_extension', 'autocomplete', 'AI code generation with real-time autocomplete and chat', 'AI autocomplete and chat', 'universal', 'freemium', 'easy', '["any"]', 'https://www.blackbox.ai'),
('Double', 'double-ai', 'ide_extension', 'assistant', 'AI coding assistant with workspace-wide context understanding', 'Workspace-aware AI assistant', 'universal', 'freemium', 'easy', '["claude-sonnet-4","gpt-4o"]', 'https://double.bot');

-- ═══ CLI Tools ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, github_url, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Goose', 'goose-ai', 'cli_tool', 'agent', 'Open-source AI developer agent by Block that automates coding tasks', 'AI coding agent by Block', 'https://github.com/block/goose', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","any-via-api"]', 'https://github.com/block/goose'),
('Mentat', 'mentat', 'cli_tool', 'agent', 'AI coding assistant that understands your entire codebase context', 'Codebase-aware coding agent', 'https://github.com/AbanteAI/mentat', 'universal', 'free', 'medium', '["gpt-4o","claude-sonnet-4","any-via-api"]', 'https://github.com/AbanteAI/mentat'),
('Sweep', 'sweep', 'cli_tool', 'agent', 'AI-powered GitHub issue to pull request automation', 'GitHub issue to PR bot', 'https://github.com/sweepai/sweep', 'universal', 'freemium', 'medium', '["gpt-4o","claude-sonnet-4"]', 'https://sweep.dev'),
('Claude Engineer', 'claude-engineer', 'cli_tool', 'agent', 'Interactive CLI for software engineering with Claude', 'Claude-powered CLI engineer', 'https://github.com/Doriandarko/claude-engineer', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4"]', 'https://github.com/Doriandarko/claude-engineer'),
('Codegen', 'codegen-tool', 'cli_tool', 'refactoring', 'Programmatic code manipulation and large-scale refactoring tool', 'Programmatic code refactoring', 'https://github.com/codegen-sh/codegen-sdk', 'universal', 'freemium', 'medium', '["any"]', 'https://codegen.sh'),
('Devika', 'devika', 'cli_tool', 'agent', 'Open-source AI software engineer that can plan, research, and code', 'AI software engineer agent', 'https://github.com/stitionai/devika', 'universal', 'free', 'medium', '["gpt-4o","claude-sonnet-4","any-via-api"]', 'https://github.com/stitionai/devika'),
('SWE-agent', 'swe-agent', 'cli_tool', 'agent', 'Autonomous SWE agent that resolves GitHub issues', 'GitHub issue resolver agent', 'https://github.com/princeton-nlp/SWE-agent', 'universal', 'free', 'hard', '["gpt-4o","claude-sonnet-4","any-via-api"]', 'https://github.com/princeton-nlp/SWE-agent'),
('Devin', 'devin', 'cli_tool', 'agent', 'Autonomous AI software engineer by Cognition with full dev environment', 'Autonomous AI engineer', 'universal', 'paid', 'easy', '["any"]', 'https://devin.ai'),
('Copilot CLI', 'github-copilot-cli', 'cli_tool', 'shell', 'AI-powered command-line tool by GitHub for shell commands', 'AI shell command helper', 'https://github.com/github/gh-copilot', 'universal', 'paid', 'easy', '["gpt-4o"]', 'https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-command-line'),
('Amazon CodeWhisperer CLI', 'codewhisperer-cli', 'cli_tool', 'autocomplete', 'AI code suggestions for the command line from AWS', 'AWS AI shell assistant', 'universal', 'free', 'easy', '["any"]', 'https://aws.amazon.com/codewhisperer/'),
('Ollama', 'ollama', 'cli_tool', 'runtime', 'Run open-source LLMs locally with simple CLI', 'Local LLM runner', 'https://github.com/ollama/ollama', 'universal', 'free', 'easy', '["llama-3.3-70b","deepseek-r1","deepseek-v3","any-local"]', 'https://ollama.com'),
('LM Studio', 'lm-studio', 'cli_tool', 'runtime', 'Desktop app for running local LLMs with chat UI and API', 'Local LLM desktop app', 'universal', 'free', 'easy', '["llama-3.3-70b","deepseek-r1","deepseek-v3","any-local"]', 'https://lmstudio.ai'),
('llama.cpp', 'llama-cpp', 'cli_tool', 'runtime', 'High-performance C++ inference for LLMs on CPU and GPU', 'Fast local LLM inference', 'https://github.com/ggerganov/llama.cpp', 'universal', 'free', 'hard', '["any-local"]', 'https://github.com/ggerganov/llama.cpp'),
('Jan', 'jan-ai', 'cli_tool', 'runtime', 'Open-source offline AI assistant with local model support', 'Offline AI assistant', 'https://github.com/janhq/jan', 'universal', 'free', 'easy', '["any-local"]', 'https://jan.ai');

-- ═══ Frameworks & SDKs ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, github_url, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Vercel AI SDK', 'vercel-ai-sdk', 'framework', 'sdk', 'TypeScript toolkit for building AI-powered applications with streaming', 'AI app building toolkit', 'https://github.com/vercel/ai', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro","any-via-api"]', 'https://sdk.vercel.ai'),
('LlamaIndex', 'llamaindex', 'framework', 'rag', 'Data framework for LLM applications with retrieval augmentation', 'RAG framework for LLMs', 'https://github.com/run-llama/llama_index', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","any-via-api"]', 'https://docs.llamaindex.ai'),
('Haystack', 'haystack', 'framework', 'rag', 'Open-source framework for building NLP pipelines and RAG applications', 'NLP pipeline framework', 'https://github.com/deepset-ai/haystack', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","any-via-api"]', 'https://docs.haystack.deepset.ai'),
('Semantic Kernel', 'semantic-kernel', 'framework', 'sdk', 'Microsoft SDK for integrating AI models into applications', 'Microsoft AI integration SDK', 'https://github.com/microsoft/semantic-kernel', 'universal', 'free', 'medium', '["gpt-4o","gpt-4.1","claude-sonnet-4","any-via-api"]', 'https://github.com/microsoft/semantic-kernel'),
('DSPy', 'dspy', 'framework', 'optimization', 'Framework for programming with foundation models using optimized prompts', 'LLM prompt optimization', 'https://github.com/stanfordnlp/dspy', 'universal', 'free', 'hard', '["any-via-api"]', 'https://github.com/stanfordnlp/dspy'),
('Instructor', 'instructor', 'framework', 'structured-output', 'Structured extraction from LLMs using Pydantic models', 'Structured LLM output', 'https://github.com/jxnl/instructor', 'universal', 'free', 'easy', '["claude-opus-4","claude-sonnet-4","gpt-4o","any-via-api"]', 'https://python.useinstructor.com'),
('Marvin', 'marvin', 'framework', 'structured-output', 'AI toolkit for building natural language interfaces in Python', 'NL interface toolkit', 'https://github.com/PrefectHQ/marvin', 'universal', 'free', 'easy', '["gpt-4o","claude-sonnet-4","any-via-api"]', 'https://www.askmarvin.ai'),
('Pydantic AI', 'pydantic-ai', 'framework', 'agent', 'Agent framework from Pydantic team with type-safe tool calling', 'Type-safe AI agent framework', 'https://github.com/pydantic/pydantic-ai', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","gemini-2.5-pro","any-via-api"]', 'https://ai.pydantic.dev'),
('Smolagents', 'smolagents', 'framework', 'agent', 'Lightweight agent framework by Hugging Face for tool-using AI', 'HuggingFace agent framework', 'https://github.com/huggingface/smolagents', 'universal', 'free', 'medium', '["any-via-api"]', 'https://huggingface.co/docs/smolagents'),
('Mastra', 'mastra', 'framework', 'agent', 'TypeScript framework for building AI agents and workflows', 'TS AI agent framework', 'https://github.com/mastra-ai/mastra', 'universal', 'free', 'medium', '["claude-opus-4","claude-sonnet-4","gpt-4o","any-via-api"]', 'https://mastra.ai');

-- ═══ Web-Based Tools ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Replit Agent', 'replit-agent', 'web_tool', 'agent', 'AI agent that builds full applications in Replit from natural language', 'Build apps via conversation', 'web', 'freemium', 'easy', '["claude-sonnet-4","gpt-4o"]', 'https://replit.com/agent'),
('StackBlitz Bolt', 'stackblitz-bolt', 'web_tool', 'scaffolding', 'AI-powered web development in the browser with instant preview', 'Browser-based AI dev tool', 'web', 'freemium', 'easy', '["claude-sonnet-4"]', 'https://bolt.new'),
('GitHub Spark', 'github-spark', 'web_tool', 'scaffolding', 'AI tool for creating micro apps directly from GitHub', 'AI micro-app builder', 'web', 'freemium', 'easy', '["gpt-4o"]', 'https://githubnext.com/projects/github-spark'),
('ChatGPT Canvas', 'chatgpt-canvas', 'web_tool', 'editor', 'Collaborative AI writing and coding canvas by OpenAI', 'AI coding canvas', 'web', 'freemium', 'easy', '["gpt-4o","gpt-4.1"]', 'https://openai.com/index/introducing-canvas/'),
('Claude Artifacts', 'claude-artifacts', 'web_tool', 'editor', 'Interactive code previews and documents in Claude conversations', 'Interactive code in Claude chat', 'web', 'freemium', 'easy', '["claude-opus-4","claude-sonnet-4"]', 'https://claude.ai'),
('Gemini Code Assist', 'gemini-code-assist', 'web_tool', 'assistant', 'Google Cloud AI coding assistant in Cloud Shell and IDEs', 'Google Cloud AI assistant', 'web', 'freemium', 'easy', '["gemini-2.5-pro","gemini-2.5-flash"]', 'https://cloud.google.com/products/gemini/code-assist'),
('Phind', 'phind', 'web_tool', 'search', 'AI-powered search engine optimized for developer questions', 'AI developer search engine', 'web', 'free', 'easy', '["any"]', 'https://www.phind.com'),
('Perplexity', 'perplexity', 'web_tool', 'search', 'AI search with real-time citations for coding research', 'AI search with citations', 'web', 'freemium', 'easy', '["any"]', 'https://www.perplexity.ai');

-- ═══ Code Quality & DevOps ═══
INSERT OR IGNORE INTO coding_tools (name, slug, category, subcategory, description, short_description, github_url, platform, pricing, setup_complexity, compatible_models, install_url)
VALUES
('Snyk Code', 'snyk-code', 'cli_tool', 'security', 'AI-powered code security scanning with real-time vulnerability detection', 'AI security scanner', 'universal', 'freemium', 'easy', '["any"]', 'https://snyk.io/product/snyk-code/'),
('Sourcery', 'sourcery', 'ide_extension', 'refactoring', 'AI code reviewer and refactoring tool for Python', 'AI Python refactoring', 'universal', 'freemium', 'easy', '["any"]', 'https://sourcery.ai'),
('Codacy', 'codacy', 'web_tool', 'quality', 'Automated code review with AI-powered suggestions', 'AI code review platform', 'web', 'freemium', 'easy', '["any"]', 'https://www.codacy.com'),
('PR Agent', 'pr-agent', 'cli_tool', 'review', 'AI-powered pull request analysis and review by CodiumAI', 'AI PR reviewer', 'https://github.com/Codium-ai/pr-agent', 'universal', 'freemium', 'medium', '["gpt-4o","claude-sonnet-4"]', 'https://github.com/Codium-ai/pr-agent'),
('Graphite', 'graphite', 'cli_tool', 'git', 'AI-enhanced stacking workflow for faster code review and merging', 'AI stacked PRs', 'universal', 'freemium', 'medium', '["any"]', 'https://graphite.dev'),
('GitButler', 'gitbutler', 'cli_tool', 'git', 'Git client with virtual branches and AI commit messages', 'AI-powered git client', 'https://github.com/gitbutlerapp/gitbutler', 'universal', 'free', 'easy', '["any"]', 'https://gitbutler.com');
