INSERT OR IGNORE INTO tools (name, slug, vendor, category, website_url, pricing_page_url, description) VALUES
('Qwen Code', 'qwen-code', 'Alibaba / Qwen', 'platform', 'https://chat.qwen.ai', 'https://chat.qwen.ai', 'Qwen first-party coding and research workspace across web, desktop, mobile, and API surfaces.'),
('Kimi K', 'kimi-k', 'Moonshot AI', 'platform', 'https://www.kimi.com', 'https://www.kimi.com', 'Moonshot AI coding subscription line built around Kimi K2.5 plus the wider Kimi productivity and research stack.'),
('GLM Coding', 'glm-coding', 'Z.ai / Zhipu AI', 'platform', 'https://z.ai', 'https://z.ai', 'GLM 5.1 coding-focused subscription surface from Z.ai.'),
('MiniMax Coding', 'minimax-coding', 'MiniMax', 'platform', 'https://www.minimax.io', 'https://www.minimax.io/platform', 'MiniMax token plan for interactive coding workflows with documented third-party IDE and agent compatibility.');

INSERT OR IGNORE INTO models (name, slug, vendor, family, description, is_active, input_price_per_mtok, output_price_per_mtok, context_window) VALUES
('Qwen 3.5 Plus', 'qwen-3.5-plus', 'Alibaba / Qwen', 'Qwen', 'Qwen flagship coding-facing model surfaced inside Qwen Code.', 1, NULL, NULL, NULL),
('Kimi K2.5', 'kimi-k2.5', 'Moonshot AI', 'Kimi', 'Moonshot coding model exposed through the Kimi K membership ladder.', 1, NULL, NULL, NULL),
('GLM 5.1', 'glm-5.1', 'Z.ai / Zhipu AI', 'GLM', 'GLM 5.1 coding-oriented model used in the public GLM coding plan materials.', 1, NULL, NULL, NULL),
('MiniMax M2.7', 'minimax-m2.7', 'MiniMax', 'MiniMax', 'MiniMax flagship coding model with official token-plan reset and compatibility documentation.', 1, NULL, NULL, NULL);

INSERT OR IGNORE INTO pricing_plans (tool_id, plan_name, price_monthly, price_yearly, features, models_included, overage_model, usage_notes) VALUES
((SELECT id FROM tools WHERE slug='qwen-code'), 'Code Pro', NULL, NULL, '{"features":["Qwen Studio","Web Dev workspace","Deep Research","Search","API Platform"],"requests":"Public monthly cap details are not clearly documented","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"reference","reference_price_label":"$50/mo reference","reference_price_monthly":50,"model_anchor":"Qwen 3.5 Plus","capability_summary":"Broad first-party coding and research surface with desktop, mobile, and API coverage.","best_for":["research-heavy debugging","web builds","multi-device workflows"],"tradeoffs":["Official monthly checkout pricing was not directly extractable from the reviewed public pages","Third-party IDE integrations are less clearly documented than app surfaces"],"ide_support":["Web","iOS","Android","macOS","Windows","API Platform"],"limit_summary":"Public monthly cap and reset details were not clearly documented on the official surfaces reviewed.","limit_reset":"Not clearly documented","overage_path":"Verify current fair-use and upgrade terms before purchase","support_scope":"First-party app surfaces are documented more clearly than IDE plug-ins."}}', '["qwen-3.5-plus"]', 'verify-before-buy', 'Public pricing and cap details should be rechecked on checkout because the official page did not expose them cleanly.'),
((SELECT id FROM tools WHERE slug='kimi-k'), 'Moderato', 15, NULL, '{"features":["Kimi Code","Docs / Slides / Sheets","Deep Research"],"requests":"Entry membership tier with lighter headroom","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"official","model_anchor":"Kimi K2.5","capability_summary":"Entry Kimi coding tier that still brings the broader Kimi research and productivity surface into the workflow.","best_for":["budget daily coding","mixed docs plus code loops"],"tradeoffs":["The public membership page is clearer on tier positioning than exact hard caps"],"ide_support":["Kimi Code","Web","iOS","Android"],"limit_summary":"Entry-tier allowance with lighter priority and headroom than the upper Kimi tiers.","limit_reset":"Tier allowance details vary by membership level","overage_path":"Upgrade to the next Kimi tier for more headroom","support_scope":"Best documented as a first-party coding and research workspace rather than a third-party IDE plug-in."}}', '["kimi-k2.5"]', 'upgrade', 'Kimi emphasizes tier progression and product access; verify current hard-cap details on checkout.'),
((SELECT id FROM tools WHERE slug='kimi-k'), 'Allegretto', 31, NULL, '{"features":["Kimi Code","Deep Research","Docs / Slides / Sheets","Kimi Claw"],"requests":"Mid-tier membership with more frequent coding headroom","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"official","model_anchor":"Kimi K2.5","capability_summary":"Mid-tier Kimi option for developers who want K2.5 access without jumping straight to the heavier plans.","best_for":["regular coding sessions","research plus implementation loops"],"tradeoffs":["Exact numeric hard caps are less explicit than the plan ladder itself"],"ide_support":["Kimi Code","Kimi Claw","Web","iOS","Android"],"limit_summary":"More frequent Kimi Code use and higher priority than Moderato, but still below the heavy-use tiers.","limit_reset":"Tier allowance details vary by membership level","overage_path":"Upgrade to Allegro or Vivace when the allowance is too tight","support_scope":"First-party coding experience plus Moonshot productivity surfaces."}}', '["kimi-k2.5"]', 'upgrade', 'Good middle tier when you want Kimi K2.5 without paying for the heaviest allowance.'),
((SELECT id FROM tools WHERE slug='kimi-k'), 'Allegro', 79, NULL, '{"features":["Kimi Code","Kimi Claw","Deep Research","Agent Swarm"],"requests":"High-usage tier for heavier daily coding","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"official","model_anchor":"Kimi K2.5","capability_summary":"Heavy-use Kimi tier aimed at developers leaning on Kimi for daily coding, research, and agent workflows.","best_for":["full-day coding sessions","agent-assisted implementation"],"tradeoffs":["Still less explicit on exact hard caps than MiniMax is"],"ide_support":["Kimi Code","Kimi Claw","Agent Swarm","Web","iOS","Android"],"limit_summary":"Heavy-use tier with materially more headroom and priority than the lower Kimi plans.","limit_reset":"Tier allowance details vary by membership level","overage_path":"Upgrade to Vivace if you routinely hit the allowance","support_scope":"First-party coding workflow with Moonshot agent features layered on top."}}', '["kimi-k2.5"]', 'upgrade', 'Built for heavier daily use when Moderato or Allegretto would run out of headroom.'),
((SELECT id FROM tools WHERE slug='kimi-k'), 'Vivace', 159, NULL, '{"features":["Kimi Code","Kimi Claw","Agent Swarm","Deep Research","Priority access"],"requests":"Top Kimi tier with the most headroom and priority","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"official","model_anchor":"Kimi K2.5","capability_summary":"Top Kimi tier for buyers who want the broadest Kimi allowance and priority access inside Moonshot''s first-party stack.","best_for":["all-day agent workflows","highest Kimi priority"],"tradeoffs":["The public membership page still emphasizes positioning more than hard usage math"],"ide_support":["Kimi Code","Kimi Claw","Agent Swarm","Web","iOS","Android"],"limit_summary":"Highest-priority Kimi tier with the broadest usage headroom in the published ladder.","limit_reset":"Tier allowance details vary by membership level","overage_path":"This is the top public tier; verify Moonshot support if you need more than the published allowance","support_scope":"Strongest Kimi packaging if you want Moonshot''s first-party coding environment as the center of your workflow."}}', '["kimi-k2.5"]', 'upgrade', 'Top public Kimi tier for buyers who want the most headroom without juggling multiple memberships.'),
((SELECT id FROM tools WHERE slug='glm-coding'), 'Coding Plan', NULL, NULL, '{"features":["GLM 5.1","Coding-plan positioning","Developer workspace"],"requests":"Public monthly cap details are not clearly documented","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"reference","reference_price_label":"$30/mo reference","reference_price_monthly":30,"model_anchor":"GLM 5.1","capability_summary":"Z.ai positions GLM 5.1 as a coding-focused subscription, but the public billing details remain thin.","best_for":["GLM-first workflows","buyers comfortable verifying details before checkout"],"tradeoffs":["Public monthly checkout pricing was not directly extractable from official pages","IDE compatibility details are still sparse in the reviewed public materials"],"ide_support":[],"limit_summary":"Public limit and reset details were not clearly documented on the official pages reviewed.","limit_reset":"Not clearly documented","overage_path":"Verify allowance, upgrade, and reset behavior before purchase","support_scope":"Public IDE compatibility details were limited in the official materials reviewed."}}', '["glm-5.1"]', 'verify-before-buy', 'The public product material makes the coding positioning clear, but not the exact monthly plan rules.'),
((SELECT id FROM tools WHERE slug='minimax-coding'), 'Token Plan', NULL, NULL, '{"features":["MiniMax M2.7","High-speed variant","Third-party coding tool docs","Pay-as-you-go escape hatch"],"requests":"5-hour rolling text quota with daily non-text resets","comparison":{"track":"coding-subscription","hidden_from_catalog":true,"pricing_confidence":"reference","reference_price_label":"$20-30/mo reference","reference_price_monthly":25,"model_anchor":"MiniMax M2.7","capability_summary":"Strong coding plan if you already work inside third-party IDEs or coding agents and want clearer fallback behavior.","best_for":["Claude Code or Cursor workflows","high-frequency interactive prompting","buyers who care about documented reset behavior"],"tradeoffs":["Peak-hour rate limiting can still apply","Weekly quotas may affect newer users","Production usage is nudged toward pay-as-you-go"],"ide_support":["OpenClaw","OpenCode","Claude Code","Cursor","Trae","Cline","Roo Code","Zed"],"limit_summary":"M2.7 text quotas use a 5-hour rolling window; non-text quotas reset daily; peak-hour rate limiting and weekly quotas can apply.","limit_reset":"5-hour rolling for text, daily for non-text","overage_path":"Upgrade, switch to pay-as-you-go, or wait for reset","support_scope":"Official docs explicitly list third-party coding agents and editors.","sources_note":"FAQ and token-plan docs expose the clearest limit and compatibility details in this comparison set."}}', '["minimax-m2.7"]', 'upgrade-or-payg', 'Official docs are unusually clear on reset behavior, fallbacks, and supported coding tools.');

INSERT OR IGNORE INTO model_availability (model_id, tool_id, plan_id, access_level, cost_notes) VALUES
((SELECT id FROM models WHERE slug='qwen-3.5-plus'), (SELECT id FROM tools WHERE slug='qwen-code'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='qwen-code') AND plan_name='Code Pro'), 'full', 'Qwen Code positions Qwen 3.5 Plus as the coding model anchor, but public plan-limit details are sparse.'),
((SELECT id FROM models WHERE slug='kimi-k2.5'), (SELECT id FROM tools WHERE slug='kimi-k'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='kimi-k') AND plan_name='Moderato'), 'full', 'Entry Kimi membership tier.'),
((SELECT id FROM models WHERE slug='kimi-k2.5'), (SELECT id FROM tools WHERE slug='kimi-k'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='kimi-k') AND plan_name='Allegretto'), 'full', 'Mid-tier Kimi membership with more headroom.'),
((SELECT id FROM models WHERE slug='kimi-k2.5'), (SELECT id FROM tools WHERE slug='kimi-k'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='kimi-k') AND plan_name='Allegro'), 'full', 'Heavy-use Kimi membership tier.'),
((SELECT id FROM models WHERE slug='kimi-k2.5'), (SELECT id FROM tools WHERE slug='kimi-k'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='kimi-k') AND plan_name='Vivace'), 'full', 'Top public Kimi membership tier.'),
((SELECT id FROM models WHERE slug='glm-5.1'), (SELECT id FROM tools WHERE slug='glm-coding'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='glm-coding') AND plan_name='Coding Plan'), 'full', 'GLM coding-plan product materials emphasize GLM 5.1 but leave plan rules sparse.'),
((SELECT id FROM models WHERE slug='minimax-m2.7'), (SELECT id FROM tools WHERE slug='minimax-coding'), (SELECT id FROM pricing_plans WHERE tool_id=(SELECT id FROM tools WHERE slug='minimax-coding') AND plan_name='Token Plan'), 'full', 'Official token-plan docs specify reset logic, fallback options, and supported coding tools.');